name: hannds

channels:
  - conda-forge

dependencies:
  - python=3.5
  - setuptools
  - numpy
  - numba
  - scipy
  - pyqt
  - matplotlib
  - pip
  - pip:
    - mido
    - git+https://github.com/craffel/pretty-midi.git
    - tensorflow-gpu
