name: hannds

channels:
  - conda-forge

dependencies:
  - python=3.5
  - setuptools
  - pyqt
  - numpy
  - numba
  - scipy
  - matplotlib
  - pip
  - pip:
    - mido
    - https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.3.0-cp35-cp35m-win_amd64.whl
