name: pytorch

channels:
  - pytorch

dependencies:
  - python=3.6
  - tensorboard
  - matplotlib
  - pytorch
  - cudatoolkit
  - pip
  - pip:
    - mido
    - git+https://github.com/craffel/pretty-midi.git
    - tensorboardx
