name: hannds

channels:
  - pytorch

dependencies:
  - python=3.6
  - matplotlib
  - pytorch
  - pytest
  - scipy
  - pip
  - pip:
    - mido
    - git+https://github.com/craffel/pretty-midi.git
    - tensorboardx
    - python-osc
